#!/bin/bash

####################################################################################################
#                                                                                                  #
# (c) 2018 Quantstamp, Inc. All rights reserved.  This content shall not be used, copied,          #
# modified, redistributed, or otherwise disseminated except to the extent expressly authorized by  #
# Quantstamp for credentialed users. This content and its use are governed by the Quantstamp       #
# Demonstration License Terms at <insert link>.                                                    #
#                                                                                                  #
####################################################################################################

# Imports common definitions
source "$WRAPPER_HOME"/utils/common

# Pull oyente's docker image
docker pull "$DOCKER_IMAGE" || exit 1
