#!/bin/bash

####################################################################################################
#                                                                                                  #
# (c) 2018, 2019 Quantstamp, Inc. This content and its use are governed by the license terms at    #
# <https://s3.amazonaws.com/qsp-protocol-license/V2_LICENSE.txt>                                   #
#                                                                                                  #
####################################################################################################

# NOTE: This script is for testing purposes only; it allows executing different
# wrapper scripts as a means to debug their output

function usage {
  echo "Usage: wrapper_exec <name> <script> <args> <target contract>" >> /dev/stderr
}

if [[ "$#" != "4" ]] ; then
   usage
   exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
SCRIPT="$2"

if [[ "x$QSP_HOME" == "x" ]] ; then
    export QSP_HOME=$(cd ../../../ && pwd)
fi

if [[ "x$QSP_HOST_USOLC" == "x" ]] ; then
    export QSP_HOST_USOLC="$QSP_HOME/bin/solc"
fi

if [[ "x$QSP_CONTAINER_USOLC" == "x" ]] ; then
    export QSP_CONTAINER_USOLC="/opt/usolc/bin/solc"
fi

if [[ "x$QSP_DOCKER_SOCKET" == "x" ]] ; then
    export QSP_DOCKER_SOCKET="/var/run/docker.sock"
fi

export ANALYZER_NAME="$1"
export WRAPPER_HOME="$SCRIPT_DIR/$ANALYZER_NAME"
export STORAGE_DIR="/tmp"

ARGS=("$@")
export ANALYZER_ARGS="${ARGS[2]}"
export CONTRACT_PATH=$(realpath "${ARGS[3]}")
export ORIGINAL_FILE_NAME=$(echo "$CONTRACT_PATH" | awk -F '/' '{ print $NF }' )
export CONTRACT_FILE_NAME="$ORIGINAL_FILE_NAME"

source common/settings

on_exit_do rm -f "$STORAGE_DIR"/.once

"$WRAPPER_HOME"/"$SCRIPT"

