#!/bin/bash

####################################################################################################
#                                                                                                  #
# (c) 2018, 2019 Quantstamp, Inc. This content and its use are governed by the license terms at    #
# <https://s3.amazonaws.com/qsp-protocol-license/V2_LICENSE.txt>                                   #
#                                                                                                  #
####################################################################################################

source "$WRAPPER_HOME"/../common/settings

# Pull docker image
"$WRAPPER_HOME"/../common/pull_analyzer || exit 1
