#!/usr/bin/env python

####################################################################################################
#                                                                                                  #
# (c) 2018 Quantstamp, Inc. All rights reserved.  This content shall not be used, copied,          #
# modified, redistributed, or otherwise disseminated except to the extent expressly authorized by  #
# Quantstamp for credentialed users. This content and its use are governed by the Quantstamp       #
# Demonstration License Terms at <insert link>.                                                    #
#                                                                                                  #
####################################################################################################

import json
import sys


def print_report(errors=[], warnings=[]):
    report = {
        'status': 'error'
    }

    if len(errors) > 0:
        report['errors'] = errors

    if len(warnings) > 0:
        report['warnings'] = warnings

    print(json.dumps(report, indent=2))


def main(argv):
    errors = []
    warnings = []
    try:
        if len(argv) != 2:
            raise Exception("Missing argument error. Usage: mk_error <errors file>")
        with open(argv[1]) as errors_file:
            errors = [error for error in errors_file]

    except Exception as e:
        errors.append(str(e))

    try:
        print_report(errors, warnings)
    except Exception as e:
        # Nothing much to do here....
        sys.exit(1)


if __name__ == "__main__":
    main(sys.argv)
