#!/bin/bash

####################################################################################################
#                                                                                                  #
# (c) 2018, 2019 Quantstamp, Inc. This content and its use are governed by the license terms at    #
# <https://s3.amazonaws.com/qsp-protocol-license/V2_LICENSE.txt>                                   #
#                                                                                                  #
####################################################################################################

source "$WRAPPER_HOME"/../common/settings

readonly ANALYZER_DOCKER_IMAGE="qspprotocol/securify:node-latest"
readonly ANALYZER_SYS_PATH=$(docker run --entrypoint /bin/bash "$ANALYZER_DOCKER_IMAGE" -c 'echo "$PATH"')
readonly ANALYZER_VERSION=$(echo "$ANALYZER_DOCKER_IMAGE" | egrep -o '[0-9A-Za-z]+$' | cut -d ':' -f2)
readonly ANALYZER_CMD="docker run --rm -e PATH=$QSP_USOLC_BIN_DIR:$ANALYZER_SYS_PATH -v $TMP_FOLDER:/shared/ -i $ANALYZER_DOCKER_IMAGE $ANALYZER_ARGS -fs /shared/$CONTRACT_FILE_NAME"

